### ISSUE TITLE
範囲にレビューしたい

### ISSUE THREAD

**Issue by chitoku-k** [himanoa/goshiteki#15]
一行ではなく、ビジュアルモード等で与えられたレンジに対してコメントが書けると嬉しい。API 的な構造は未確認。

**Comment by himanoa** [comment]
`start_line`が開始位置で、`line` が終了位置っぽい

**Comment by himanoa** [comment]
これでやりやくなってそう
https://github.com/himanoa/goshiteki/pull/17

**Comment by chitoku-k** [comment]
というか範囲レビューしたいので #17 を入れた（必須）
