### ISSUE TITLE
行数がまともじゃない

### ISSUE THREAD

**Issue by himanoa** [himanoa/goshiteki#7]
diffhunk を見てレビューコメントしたい位置までの -行も含めた行数でpositionを決定しないとまともな位置がでないっぽい！

**Comment by himanoa** [comment]
- diffhunkを見て - 行数を確定するために、レビュー対象のPull-RequestがどこのブランチにMergeされる予定なのかを取得する必要がある
  - pull-requestのqueryにbaseBranchみたいなのがあった覚えがあるのでそれを取ってくる必要がある
- そのファイルがbase-branchの時点で全体何行のファイルなのかをチェックする必要がありそう
  - `git  diff --numstat base-branch` で追加行数と削除行数がわかる
    - 現在のファイル行数 - ( `numstatの削除行数 - numstatの追加行数 ) で派生元ブランチで何行だったかわかるはず？
- それ以上下にdelete lineなdiffがないかどうかで計算方法が変わりそう？
  - 参考実装: https://github.com/microsoft/vscode-pull-request-github/blob/ee0992108bf57dace542370d23ffb9c431fab049/src/common/diffPositionMapping.ts#L122-L133

**Comment by himanoa** [comment]
本質的にやりたいのは追加したい行数の上の行に存在する- diffの行数を足した行数をpositionに渡すかな

**Comment by himanoa** [comment]
これもなんか使えそうかな hunk
```
❯ git diff -U0 master commands/review-comments.sh
diff --git a/commands/review-comments.sh b/commands/review-comments.sh
index f946345..25e9779 100755
--- a/commands/review-comments.sh
+++ b/commands/review-comments.sh
@@ -5,9 +5,2 @@ review-comments() {
-  echo "[{\"path\": \"$1\", \"position\": $2, \"body\": \"$3\"}]" > TMP.json
-  REVIEW_COMMENT_STATE="./.REVIEW_COMMENT_STATE"
-  if [ -e $REVIEW_COMMENT_STATE ]; then
-    # shellcheck disable=SC2094
-    jq -s add "$REVIEW_COMMENT_STATE" TMP.json "." > NEW_REVIEW_COMMENT_STATE
-    mv NEW_REVIEW_COMMENT_STATE "$REVIEW_COMMENT_STATE"
-  else
-    cp TMP.json "$REVIEW_COMMENT_STATE"
-  fi
+  local REVIEW_COMMENT_STATE="./.REVIEW_COMMENT_STATE"
+  local current=$(cat -- "$REVIEW_COMMENT_STATE" 2> /dev/null)
@@ -15 +8,6 @@ review-comments() {
-  rm TMP.json
+  jq \
+    --arg path "$1" \
+    --arg position "$2" \
+    --arg body "$3" \
+    'flatten + [{path: $path, position: $position | tonumber, body: $body}]' \
+    <<< "${current:-[]}" > "$REVIEW_COMMENT_STATE"
```

**Comment by himanoa** [comment]
- コメントしたい行数のdiffに到達するまでになんこ-diffがあるか数える
- どうやって？
- コメントしたい行の内容とまったく同じ内容の行が上に何個あるかを入力にとって、自身に到達するまで何個-diffがあるか数えるやつがあればいい？
```
- 人間性
+ 人間
+ 人間
- 人間が壊れてしまって悲しいねえ
+ 人間
```
- みたいなdiffの時に `countDeleteLines("人間", 2) // -> 1` を返す的な

**Comment by himanoa** [comment]
↑かなり有力な気がしてきた

**Comment by chitoku-k** [comment]
diff の hunk って API から取れないのかな？
手で計算すると GitHub で使われている diff アルゴリズムとズレやすくなる

**Comment by himanoa** [comment]
手元のファイルをベースに行数算出してるし手計算するべきな気がする…？

**Comment by himanoa** [comment]
そもそもdiffhunk取ってくるやつがなさそう

**Comment by himanoa** [comment]
https://github.com/himanoa/diffhunk-playground
書き始めたけど進捗は芳しくない

**Comment by chitoku-k** [comment]
変更のあったところから前後 3 行まで position の対象で、またぐ部分はボタンが表示されていないし Web UI ではレビューできないが番号が振られている模様。ピンクが position。
<img width="1463" alt="貼り付けた画像_2020_10_11_21_36" src="https://user-images.githubusercontent.com/6535425/95678881-47476680-0c0a-11eb-8a74-9dd20e9b050c.png">

**Comment by chitoku-k** [comment]
実装の機運が見えてきたので書いてみるね
