### ISSUE TITLE
空の LineComment でエラーが発生する

### ISSUE THREAD

**Issue by chitoku-k** [himanoa/goshiteki#9]
`:GoshitekiLineComment` を使ったあとにバッファーを終了すると空のコメントがレビューステートに残ってしまい、`:GoshitekiComment` に失敗してしまう

**Comment by himanoa** [comment]
catでファイル除いて空だったら追加しないみたいな実装をすればいい気がしてきた！

**Comment by chitoku-k** [comment]
`[[ -s filename ]]` で終わり！ｗ
